version: 0.2
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore MyApp.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet msbuild MyApp.sln
artifacts:
  files:
    - MyConsoleApp/bin/Debug/net8.0/*
